# Generated by Django 5.2.7 on 2025-11-05 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='location_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='location_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('COUPE', 'Coupe'), ('HATCH', 'Hatchback'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], default='SEDAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='rentals.dealer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['car', 'start_date', 'end_date'], name='rentals_boo_car_id_08ef3e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='rentals_boo_user_id_32d5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['active', 'price_per_day'], name='rentals_car_active_a591ca_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_type', 'transmission', 'seats'], name='rentals_car_car_typ_57cb62_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model', 'year'], name='rentals_car_make_398420_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['active', 'name'], name='rentals_dea_active_8a9636_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='booking_dates_valid'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.car'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['car', 'is_primary'], name='rentals_car_car_id_3987fd_idx'),
        ),
    ]
