# Generated by Django 5.2.7 on 2025-11-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_carimage_alter_dealer_options_and_more'),
        ('rentals', '0002_carimage_alter_dealer_options_booking_currency_and_more'),
    ]

    operations = [
    ]
