# Generated by Django 5.2.7 on 2025-11-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'indexes': [models.Index(fields=['active', 'name'], name='rentals_api_active_946066_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatch', 'Hatchback'), ('van', 'Van')], default='sedan', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('location_country', models.CharField(blank=True, max_length=120)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='rentals_api.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='rentals_api.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_selected', models.BooleanField(default=False)),
                ('insurance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals_api.car')),
            ],
            options={
                'indexes': [models.Index(fields=['car', 'start_date', 'end_date'], name='rentals_api_car_id_ac1fc3_idx'), models.Index(fields=['user_id', 'status'], name='rentals_api_user_id_372431_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='booking_dates_valid')],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals_api.car')),
            ],
            options={
                'indexes': [models.Index(fields=['car', 'is_primary'], name='rentals_api_car_id_64541c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['available', 'price_per_day'], name='rentals_api_availab_52b1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_type', 'transmission'], name='rentals_api_car_typ_599cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model', 'year'], name='rentals_api_make_3e27c6_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user_id', 'car'], name='rentals_api_user_id_294112_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_id', 'car')},
        ),
    ]
